### ISSUE TITLE
Feat : 상점 상세 조회 API 구현

### ISSUE THREAD

**Issue by salkizzang** [Cod2-Crafters/market-back#34]
1. 멤버 ID 값으로 상점 상세 정보를 조회.

2. 원하는 Response : 
{
**멤버**: {
        멤버 아이디
        상점(멤버) 이름 
        상점 설명
        상점 오픈일(최초 등록일)
        상점 방문수 -> 없는거 같음.
        상품 판매 갯수
}
**상품 리스트** : [{
        상품 아이디
        상품 썸네일
        상품 제목
        상품 가격
        상품 상태
        상품 등록일
}]  
}

- 고려 사항 
-> 최신순, 인기순, 저가순, 고가순 정렬이 있는데 소팅을 백에서? 프론트에서? (1번 이미지 참고)
-> 상품 갯수가 너무 많으면 페이징? 
-> (프론트 화면) 판매내역에서 조회가 따로 있음. API로 호출? (2번 이미지 참고)
--> 마찬가지로 찜한 상품에 대해서도 조회가 따로 있음 -> 많이 사용될지는 사용자 경험에서는 잘 모르겠음. (3번 이미지 참고)

- 참고 이미지
<figure>
<img width="434" alt="스크린샷 2024-03-18 오후 8 37 32" src="https://github.com/Cod2-Crafters/market-back/assets/124907958/637b14e4-eba8-4a6c-8ed4-792dd87a31cb">
<figcaption>1번 이미지</figcaption>
</figure>
<figure>
<img width="330" alt="스크린샷 2024-03-18 오후 8 40 57" src="https://github.com/Cod2-Crafters/market-back/assets/124907958/8c53f353-953f-4db0-851f-1e91507e1060">
<figcaption>2번 이미지</figcaption>
</figure>
<figure>
<img width="356" alt="스크린샷 2024-03-18 오후 8 42 15" src="https://github.com/Cod2-Crafters/market-back/assets/124907958/13bd7e18-94f3-4cfa-910d-ce55bbf87648">
<figcaption>3번 이미지 </figcaption>
</figure>

**Comment by jiheon2234** [comment]
@salkizzang 
멤버와 상품 리스트를 각각 api 호출

상품은 api/post/search?....... 구현중

**Comment by jiheon2234** [comment]
#35 동적검색기능 구현

**Comment by jiheon2234** [comment]
+1 리턴하던거 처리
